library(wordbankr)
library(tidyverse)
source("update_unilemmas.R")

language = "American Sign Language"
outdir = "final_instruments/"

old_items <- get_item_data(language = language, db_args = db_args) %>%
  filter(item_kind=="word")

new_items <- update_unilemmas(language, show_conflicts=T)
# "loaded 820 American Sign Language items"
# "58 missing uni_lemmas in original ( 7 % missing)"
# "174 uni_lemmas added/modified"
# "Adding uncontested new_uni_lemmas..."
# "51 uni_lemmas still missing ( 6 % missing)"
# "Review 0 suggested new_uni_lemmas that replace existing uni_lemmas, and revise by hand:"

new_items[which(new_items$uni_lemma=="sandals"),]$uni_lemma = "sandal" 
new_items[which(new_items$uni_lemma=="tv"),]$uni_lemma = "TV" 
new_items[which(new_items$uni_lemma=="band-aid"),]$uni_lemma = "bandaid" 

# now join and re-save in raw_data/instruments format, e.g.
# https://github.com/langcog/wordbank/blob/master/raw_data/BSL_WG/%5BBSL_WG%5D.csv

# load original instrument(s) file, as get_item_data doesn't have all the needed columns
#instr_name = "[BSL_WG].csv"

new_a <- update_instrument("ASL", "FormA", new_items %>% rename(itemID = A))
# ""               "and"            "bagel"          "bandaid"        "baseball"      
# "basement"       "basket"         "basketball"     "bat (object)"   "because"       
# "before"         "behind"         "belt"           "beside"         "better"        
# "birthday"       "bowling"        "brown"          "brush (action)" "build"         
# "but"            "camping"        "chase"          "circus"         "cook"          
# "corn"           "cowboy"         "crazy"          "cream cheese"   "cut"           
# "deaf"           "donut"          "dryer"          "earring"        "farm"          
# "fireman"        "first"          "fix"            "flag"           "football"      
# "forest"         "french fries"   "game"           "gas station"    "golf"          
# "grape"          "green bean"     "gum"            "hamburger"      "helicopter"    
# "hose"           "ice"            "if"             "jelly"          "knock"         
# "last"           "lawn mower"     "learn"          "letter"         "lightning"     
# "like"           "long"           "mailman"        "monster"        "mop"           
# "movie"          "napkin"         "newspaper"      "nurse"          "nut"           
# "peanut butter"  "pencil"         "pick"           "picnic"         "pink"          
# "poor"           "popsicle"       "potato chips"   "pour"           "pumpkin"       
# "purple"         "puzzle"         "quiet"          "restaurant"     "robot"         
# "salad"          "salt"           "sandal"         "santa claus"    "share"         
# "shopping"       "sign (action)"  "silly"          "skate"          "skunk"         
# "sled"           "slide (action)" "snowman"        "soon"           "sprinkler"     
# "stay"           "sticky"         "story"          "strawberry"     "stuck"         
# "syrup"          "tape"           "taste"          "teach"          "their"         
# "think"          "town"           "TV"             "vanilla"        "vitamin"       
# "waffle"         "want"           "will"           "windy"          "yourself"      
# "zebra"          "yourself"  

new_b1 <- update_instrument("ASL", "FormB1", new_items %>% rename(itemID = B1))
# ""               "about"          "and"            "bagel"          "bandaid"       
# "baseball"       "basement"       "basket"         "basketball"     "bat (object)"  
# "because"        "before"         "behind"         "belt"           "beside"        
# "better"         "birthday"       "bowling"        "brown"          "brush (action)"
# "build"          "but"            "camping"        "chase"          "choose"        
# "christmas"      "circus"         "cook"           "corn"           "cowboy"        
# "crazy"          "cream cheese"   "cut"            "deaf"           "dining room"   
# "disappointed"   "donut"          "dryer"          "each"           "earring"       
# "easter"         "farm"           "fireman"        "first"          "fit"           
# "fix"            "flag"           "football"       "forest"         "french fries"  
# "game"           "gas station"    "golf"           "grape"          "green bean"    
# "gum"            "halloween"      "hamburger"      "handsome"       "hanukkah"      
# "hate"           "hearing"        "helicopter"     "hose"           "ice"           
# "if"             "imagine"        "interpreter"    "jelly"          "knock"         
# "last"           "lawn mower"     "learn"          "letter"         "lightning"     
# "like"           "lips"           "long"           "loud"           "mailman"       
# "monster"        "month"          "mop"            "movie"          "napkin"        
# "need"           "newspaper"      "nurse"          "nut"            "onion"         
# "peanut butter"  "pencil"         "pick"           "picnic"         "pink"          
# "poor"           "popsicle"       "potato chips"   "pour"           "pumpkin"       
# "punish"         "purple"         "puzzle"         "quiet"          "restaurant"    
# "robot"          "salad"          "salt"           "sandal"         "santa claus"   
# "share"          "shopping"       "short"          "shoulder"       "sign (action)" 
# "silly"          "skate"          "skunk"          "sled"           "slide (action)"
# "snowman"        "so"             "soccer"         "soon"           "sorry"         
# "sprinkler"      "stay"           "sticky"         "story"          "strawberry"    
# "stuck"          "syrup"          "tall"           "tape"           "taste"         
# "teach"          "tent"           "their"          "then"           "think"         
# "thunder"        "ticket"         "town"           "TV"             "vacation"      
# "vanilla"        "vegetable"      "vitamin"        "volleyball"     "waffle"        
# "wake up"        "want"           "week"           "welcome"        "will"          
# "windy"          "wish"           "year"           "yourself"       "zebra" 

new_b2 <- update_instrument("ASL", "FormB2", new_items %>% rename(itemID = B2))
# ""                     "and"                  "bagel"                "bandaid"             
# "baseball"             "basement"             "basket"               "basketball"          
# "bat (object)"         "because"              "before"               "behind"              
# "belt"                 "beside"               "better"               "birthday"            
# "bowling"              "brown"                "brush (action)"       "build"               
# "but"                  "camping"              "chase"                "circus"              
# "cook"                 "corn"                 "cowboy"               "crazy"               
# "cream cheese"         "cut"                  "deaf"                 "donut"               
# "dryer"                "earring"              "farm"                 "fireman"             
# "first"                "fish (food)"          "fix"                  "flag"                
# "football"             "forest"               "french fries"         "game"                
# "gas station"          "golf"                 "grape"                "green bean"          
# "gum"                  "hamburger"            "helicopter"           "hose"                
# "ice"                  "if"                   "jelly"                "knock"               
# "last"                 "lawn mower"           "learn"                "letter"              
# "lightning"            "like"                 "long"                 "loud"                
# "mailman"              "monster"              "mop"                  "movie"               
# "napkin"               "need"                 "newspaper"            "nurse"               
# "nut"                  "orange (description)" "peanut butter"        "pencil"              
# "pick"                 "picnic"               "pink"                 "poor"                
# "popsicle"             "potato chips"         "pour"                 "pumpkin"             
# "purple"               "puzzle"               "quiet"                "restaurant"          
# "ride"                 "robot"                "salad"                "salt"                
# "sandal"               "santa claus"          "share"                "shopping"            
# "sign (action)"        "silly"                "skate"                "skunk"               
# "sled"                 "slide (action)"       "snowman"              "soon"                
# "sprinkler"            "stay"                 "sticky"               "story"               
# "strawberry"           "stuck"                "syrup"                "tape"                
# "taste"                "teach"                "their"                "think"               
# "town"                 "TV"                   "vanilla"              "vitamin"             
# "waffle"               "want"                 "water (not beverage)" "will"                
# "windy"                "yourself"             "zebra"  

new_c <- update_instrument("ASL", "FormC", new_items %>% rename(itemID = C))
# ""                     "and"                  "bagel"                "bandaid"             
# "baseball"             "basement"             "basket"               "basketball"          
# "bat (object)"         "because"              "before"               "behind"              
# "belt"                 "beside"               "better"               "birthday"            
# "bowling"              "brown"                "brush (action)"       "build"               
# "but"                  "camping"              "chase"                "circus"              
# "cook"                 "corn"                 "cowboy"               "crazy"               
# "cream cheese"         "cut"                  "deaf"                 "donut"               
# "dryer"                "earring"              "farm"                 "fireman"             
# "first"                "fish (food)"          "fix"                  "flag"                
# "football"             "forest"               "french fries"         "game"                
# "gas station"          "golf"                 "grape"                "green bean"          
# "gum"                  "hamburger"            "helicopter"           "hose"                
# "ice"                  "if"                   "jelly"                "knock"               
# "last"                 "lawn mower"           "learn"                "letter"              
# "lightning"            "like"                 "long"                 "loud"                
# "mailman"              "monster"              "mop"                  "movie"               
# "napkin"               "need"                 "newspaper"            "nurse"               
# "nut"                  "orange (food)"        "peanut butter"        "pencil"              
# "pick"                 "picnic"               "pink"                 "poor"                
# "popsicle"             "potato chips"         "pour"                 "pumpkin"             
# "purple"               "puzzle"               "quiet"                "restaurant"          
# "ride"                 "robot"                "salad"                "salt"                
# "sandal"               "santa claus"          "share"                "shopping"            
# "sign (action)"        "silly"                "skate"                "skunk"               
# "sled"                 "slide (action)"       "snowman"              "soon"                
# "sprinkler"            "stay"                 "sticky"               "story"               
# "strawberry"           "stuck"                "syrup"                "tape"                
# "taste"                "teach"                "their"                "think"               
# "town"                 "TV"                   "vanilla"              "vitamin"             
# "waffle"               "want"                 "water (not beverage)" "will"                
# "windy"                "yourself"             "zebra"  

new_cdi2 <- update_instrument("ASL", "CDITwo", new_items %>% rename(itemID = CDITwo))
# ""         "1SG.POSS" "3SG"      "3SG.POSS" "TV" 